#!/bin/bash
while getopts ":srb" opt; do
  case "${opt}" in
    s)
      g++ main.cpp -o main.exe
      ./main.exe
      ;;
    r)
      cd 3DRendering || exit
      make
      ./render.exe
      cd ../3DRendering || exit
      ;;  
    b)
      g++ main.cpp -O2 -llapack -lblas -o -I "C:\Users\Connor\source\repos\ckuzyns\NumericalSimulatorCPP\include\eigen-3.4.0\eigen3" main.exe
      ./main.exe || exit
      cd 3DRendering || exit
      make
      ./render.exe
      cd ../3DRendering || exit
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      exit 1
      ;;
    :)
      echo "Option -$OPTARG requires an argument." >&2
      exit 1
      ;;
  esac
done

